In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [2]:
R0 = np.array([[1.0 , 0.0, 0.0],
               [0.0, 0.8, -0.6],
               [0.0, 0.6, 0.8]])
R0

array([[ 1. ,  0. ,  0. ],
       [ 0. ,  0.8, -0.6],
       [ 0. ,  0.6,  0.8]])

In [3]:
R1 = np.array([[0.8, 0.0, -0.6],
               [0.0, 1.0, 0.0],
               [0.6, 0.0, 0.8]])
R1

array([[ 0.8,  0. , -0.6],
       [ 0. ,  1. ,  0. ],
       [ 0.6,  0. ,  0.8]])

In [4]:
R0 @ R1

array([[ 0.8 ,  0.  , -0.6 ],
       [-0.36,  0.8 , -0.48],
       [ 0.48,  0.6 ,  0.64]])

In [5]:
R1 @ R0

array([[ 0.8 , -0.36, -0.48],
       [ 0.  ,  0.8 , -0.6 ],
       [ 0.6 ,  0.48,  0.64]])