In [1]:
import numpy as np

In [2]:
a = np.array([[2.0, 3.0],
              [1.0, 2.0]])
a

array([[2., 3.],
       [1., 2.]])

In [3]:
b = np.linalg.inv(a)
b

array([[ 2., -3.],
       [-1.,  2.]])

In [4]:
b @ a

array([[1., 0.],
       [0., 1.]])

In [5]:
a @ b

array([[1., 0.],
       [0., 1.]])

In [6]:
c = np.array([[1.0, 1.0],
              [1.00000001, 1.0]])
c

array([[1.        , 1.        ],
       [1.00000001, 1.        ]])

In [7]:
d = np.linalg.inv(c)
d

array([[-1.00000001e+08,  1.00000001e+08],
       [ 1.00000002e+08, -1.00000001e+08]])

In [8]:
d @ c

array([[1., 0.],
       [0., 1.]])

In [9]:
(d @ c) [0, 1]

0.0

In [10]:
n = 30

In [12]:
x = np.triu(2*np.eye(n)- np.ones((n, n)))
x

array([[ 1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1.],
       [ 0.,  1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1.],
       [ 0.,  0.,  1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1.],
       [ 0.,  0.,  0.,  1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1.],
       [ 0.,  0.,  0.,  0.,  1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1., -1., -1., -1., -1., -1.,

In [14]:
np.linalg.inv(x)

array([[1.00000000e+00, 1.00000000e+00, 2.00000000e+00, 4.00000000e+00,
        8.00000000e+00, 1.60000000e+01, 3.20000000e+01, 6.40000000e+01,
        1.28000000e+02, 2.56000000e+02, 5.12000000e+02, 1.02400000e+03,
        2.04800000e+03, 4.09600000e+03, 8.19200000e+03, 1.63840000e+04,
        3.27680000e+04, 6.55360000e+04, 1.31072000e+05, 2.62144000e+05,
        5.24288000e+05, 1.04857600e+06, 2.09715200e+06, 4.19430400e+06,
        8.38860800e+06, 1.67772160e+07, 3.35544320e+07, 6.71088640e+07,
        1.34217728e+08, 2.68435456e+08],
       [0.00000000e+00, 1.00000000e+00, 1.00000000e+00, 2.00000000e+00,
        4.00000000e+00, 8.00000000e+00, 1.60000000e+01, 3.20000000e+01,
        6.40000000e+01, 1.28000000e+02, 2.56000000e+02, 5.12000000e+02,
        1.02400000e+03, 2.04800000e+03, 4.09600000e+03, 8.19200000e+03,
        1.63840000e+04, 3.27680000e+04, 6.55360000e+04, 1.31072000e+05,
        2.62144000e+05, 5.24288000e+05, 1.04857600e+06, 2.09715200e+06,
        4.19430400e+06,

In [15]:
2.0**30

1073741824.0

In [16]:
np.linalg.inv(x) [0 , -1]

268435456.0

In [17]:
2.0**29

536870912.0

In [18]:
2.0**28

268435456.0