In [3]:
import matplotlib.pyplot as plt
import numpy as np

In [4]:
v = np.empty((7, 10), dtype = float)

v[: ,0] = np.array([1, 1, 1, 0, 1, 1, 1])
v[: ,1] = np.array([0, 0, 1, 0, 0, 1, 0])
v[: ,2] = np.array([1, 0, 1, 1, 1, 0, 1])
v[: ,3] = np.array([1, 0, 1, 1, 0, 1, 1])
v[: ,4] = np.array([0, 1, 1, 1, 0, 1, 0])
v[: ,5] = np.array([1, 1, 0, 1, 0, 1, 1])
v[: ,6] = np.array([1, 1, 0, 1, 1, 1, 1])
v[: ,7] = np.array([1, 0, 1, 0, 0, 1, 0])
v[: ,8] = np.array([1, 1, 1, 1, 1, 1, 1])
v[: ,9] = np.array([1, 1, 1, 1, 0, 1, 1])
v


array([[1., 0., 1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 0., 0., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1., 0., 1., 1.],
       [1., 0., 1., 0., 0., 0., 1., 0., 1., 0.],
       [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 0., 1., 1., 0., 1., 1.]])

In [5]:
u = np.array([1, 0, 0, 1, 0, 1, 1], dtype = float) [:, np.newaxis]
u

array([[1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.]])

In [6]:
#indre produkt af sølje 0 i v med u
v[:, [0]].T @ u 

array([[3.]])

In [7]:
v[:, [8]].T @ u

array([[4.]])

In [8]:
(v.T).shape

(10, 7)

In [9]:
#indre produkter af alle søljer i v med u
v.T @ u

array([[3.],
       [1.],
       [3.],
       [4.],
       [2.],
       [4.],
       [4.],
       [2.],
       [4.],
       [4.]])

In [10]:
v_normaliseret = np.empty_like(v)
for i in range(10):
    v_normaliseret[:, [i]] = v[:, [i]] / np.linalg.norm(v[:, [i]])
v_normaliseret

array([[0.40824829, 0.        , 0.4472136 , 0.4472136 , 0.        ,
        0.4472136 , 0.40824829, 0.57735027, 0.37796447, 0.40824829],
       [0.40824829, 0.        , 0.        , 0.        , 0.5       ,
        0.4472136 , 0.40824829, 0.        , 0.37796447, 0.40824829],
       [0.40824829, 0.70710678, 0.4472136 , 0.4472136 , 0.5       ,
        0.        , 0.        , 0.57735027, 0.37796447, 0.40824829],
       [0.        , 0.        , 0.4472136 , 0.4472136 , 0.5       ,
        0.4472136 , 0.40824829, 0.        , 0.37796447, 0.40824829],
       [0.40824829, 0.        , 0.4472136 , 0.        , 0.        ,
        0.        , 0.40824829, 0.        , 0.37796447, 0.        ],
       [0.40824829, 0.70710678, 0.        , 0.4472136 , 0.5       ,
        0.4472136 , 0.40824829, 0.57735027, 0.37796447, 0.40824829],
       [0.40824829, 0.        , 0.4472136 , 0.4472136 , 0.        ,
        0.4472136 , 0.40824829, 0.        , 0.37796447, 0.40824829]])

In [11]:
u_normaliseret = u / np.linalg.norm(u)
u_normaliseret

array([[0.5],
       [0. ],
       [0. ],
       [0.5],
       [0. ],
       [0.5],
       [0.5]])

In [12]:
v_normaliseret

array([[0.40824829, 0.        , 0.4472136 , 0.4472136 , 0.        ,
        0.4472136 , 0.40824829, 0.57735027, 0.37796447, 0.40824829],
       [0.40824829, 0.        , 0.        , 0.        , 0.5       ,
        0.4472136 , 0.40824829, 0.        , 0.37796447, 0.40824829],
       [0.40824829, 0.70710678, 0.4472136 , 0.4472136 , 0.5       ,
        0.        , 0.        , 0.57735027, 0.37796447, 0.40824829],
       [0.        , 0.        , 0.4472136 , 0.4472136 , 0.5       ,
        0.4472136 , 0.40824829, 0.        , 0.37796447, 0.40824829],
       [0.40824829, 0.        , 0.4472136 , 0.        , 0.        ,
        0.        , 0.40824829, 0.        , 0.37796447, 0.        ],
       [0.40824829, 0.70710678, 0.        , 0.4472136 , 0.5       ,
        0.4472136 , 0.40824829, 0.57735027, 0.37796447, 0.40824829],
       [0.40824829, 0.        , 0.4472136 , 0.4472136 , 0.        ,
        0.4472136 , 0.40824829, 0.        , 0.37796447, 0.40824829]])

In [14]:
cosines = v_normaliseret.T @ u_normaliseret
cosines

array([[0.61237244],
       [0.35355339],
       [0.67082039],
       [0.89442719],
       [0.5       ],
       [0.89442719],
       [0.81649658],
       [0.57735027],
       [0.75592895],
       [0.81649658]])

In [16]:
cosines.max()

0.8944271909999159

In [17]:
np.argwhere(cosines == cosines.max())

array([[3, 0],
       [5, 0]], dtype=int64)

In [18]:
a = np.array([1.0, 2.0, 3.0]) [:, np.newaxis]
b = np.array([-1.0, 3.0, -4.0]) [:, np.newaxis]

In [19]:
a.T @ b

array([[-7.]])

In [20]:
(a.T @ b) [0, 0]

-7.0

In [21]:
np.vdot(a, b)

-7.0